name: Release on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from file
        id: extract_version
        run: |
          echo "version=$(cat version) >> $GITHUB_OUTPUT"
      - name: Get commit messages
        id: get_commit_messages
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
          | jq -r '.[].commit.message' > release_body.txt

      - name: Update version in file
        run: |
          sed -i "s/VERSION_IDENTIFIER/${{ steps.extract_version.outputs.version }}/g" fxmanifest.lua

      - name: Generate Release
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: release
        run: gh release create v${{ steps.extract_version.outputs.version }} --generate-notes
